server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Log each sql query
    show-sql: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        # = JPA / HIBERNATE
        # ===============================
        # Session per thread
        current_session_context_class: thread