server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Log each sql query
  jpa:
    show-sql: true
    properties:
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      # = JPA / HIBERNATE
      # ===============================
      # Session per thread
      hibernate.current_session_context_class: thread
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect